project:
  type: website
  
website:
  title: "Hugo Åkerstrand"
  site-url: https://hugoakerstrand.com
  description: "Life science researcher and R programmer."
  back-to-top-navigation: true
  search: false
  navbar:
    right:
    - text: About
      href: about/index.qmd
    - text: Blog
      href: blog/index.qmd
    - text: dataviz
      menu: 
        - text: "Tidy Tuesday"
          href: dataviz/tidy_tuesday/index.qmd
        - text: "Swedish Politics"
          href: dataviz/swedish_politics/index.qmd
    - text: Projects
      menu: 
        - text: "R packages" 
          href: projects/r_packages/index.qmd
        - text: "Applications"
          href: projects/shiny_applications/index.qmd
  
  page-footer: 
    left: >- 
      &#169; 2025 Hugo Åkerstrand | 
      Made with [Quarto](https://quarto.org) | 
      <a href=https://github.com/hugoakerstrand/website/> {{< fa brands github >}}</a>
    center: |
      <a href=https://www.linkedin.com/in/hugo-%C3%A5kerstrand-74696655/> {{< fa brands linkedin >}}</a>
      <a href=https://github.com/hugoakerstrand/> {{< fa brands github >}}</a>
      <a href=https://pubmed.ncbi.nlm.nih.gov/?term=%C3%85kerstrand+H&cauthor_id=35088351> {{< ai pubmed >}}</a>
      <a href=https://orcid.org/0000-0003-2457-0764> {{< ai orcid >}}</a>
      <a href=mailto:hugo.akerstrand@gmail.com/>  {{< fa solid envelope >}}</a>

format:
  html:
    css: _files/styles.css
    theme: 
      light: 
        - cosmo
        - _files/theme_light.scss
        - _files/fonts.scss 
      dark: 
        - cosmo
        - _files/theme_dark.scss
        - _files/fonts.scss 
    respect-user-color-scheme: true
    fontawesome: true
    embed-resources: false  # Changed from true - CRITICAL for performance: prevents 23MB HTML file
    link-external-newwindow: true
    page-layout: full
    
execute:
  freeze: auto
    