project:
  type: website
  
website:
  title: "Hugo Ã…kerstrand"
  site-url: https://hugoakerstrand.com
  
  navbar:
    tools:
    - icon: github
      href: https://github.com/hugoakerstrand/website